include::generic-attributes.adoc[]

[#pr-deployment]
== Deployment

The following procedures describe how to deploy {productname} ({productnameshort}) on a {kube} cluster.

[#pr-deployment-prerequisites]
=== Prerequisites
* A {kube} cluster version 1.20 or higher
* {helm} version 3.2.0 or higher
* Persistent Volume (PV) provisioner support in your infrastructure
* An active subscription for {productname}

[#pr-deployment-kube-secrets]
=== Obtaining {kube} secrets from the {scc}
To download and install the {productnameshort} images from {sregistry}, you need a {kube} secret with {scc} ({scca}) mirroring credentials.
To obtain the credentials from {scca}, follow these steps:

. Visit {scc} at https://scc.suse.com and log in.
. Select the organization with an active {productnameshort} subscription from the left sidebar.
. Select `Proxies` in the top menu. The credentials are displayed in the top right corner.
. To see the password, click the 'eye' icon.
. Create a `password.txt` file containing the obtained password.
. Store the mirroring credentials retrieved from {scca} as {kube} secrets by running the following command:
[source]
  $ kubectl create secret docker-registry suse-registry \
  --docker-server=registry.suse.com --docker-username=<SUSE_REGISTRY_USERNAME> \
  --docker-password=$(head -1 ./password.txt)

[#pr-deployment-installing-and-running]
=== Installing and running {productnameshort} using {helm}
The following procedure describes how to install {productnameshort} using {helm}.
Replace `<RELEASE_NAME>` with your custom release name for the {helm} chart deployment.

. Log in to {sregistry} using the obtained {scca} mirroring credentials.
[source]
  $ head -1 ./password.txt | helm registry login registry.suse.com \
  --username <SUSE_REGISTRY_USERNAME> --password-stdin
. Install the latest version of the {productnameshort} {helm} chart.
  To change the default installation values, refer to <<pr-helm-chart-override>>.
[source]
  $ helm install <RELEASE_NAME> oci://registry.suse.com/private-registry/private-registry-helm
. The above `helm  install ...` command starts deploying several related containers.
  The deployment may take several minutes to complete.
  It also prints a message with the URL to the {productnameshort} Web portal and commands to obtain the administrator credentials.

[#pr-deployment-upgrading]
=== Upgrading {productnameshort}
To upgrade the release of the {helm} chart to a specific newer version, run the following command:
[source]
$ helm upgrade <RELEASE_NAME> oci://registry.suse.com/private-registry/private-registry-helm \
--version 1.0.0
