include::attributes.adoc[]
[#pr-ha-helm-chart-example]
== Example of {productnameshort} HA setup {helm} chart

The following example `values.yaml` file illustrates values that are required for the {productnameshort} HA setup.

[source,yaml]
----
expose:
  ingress:
    hosts:
      core: core.harbor.domain

externalURL: https://core.harbor.domain

portal:
  replicas: 2

core:
  replicas: 2

jobservice:
  replicas: 2

registry:
  replicas: 2

database:
  type: external
  external: // <1>
    host: "192.168.0.1"
    port: "5432"
    username: "user"
    password: "password"
    coreDatabase: "registry"
    existingSecret: "" //<2>
    sslmode: "disable" //<3>

redis:
  type: external
  external: //<4>
    addr: "192.168.0.2:6379" //<5>
    sentinelMasterSet: "" //<6>
    coreDatabaseIndex: "0" //<7>
    jobserviceDatabaseIndex: "1"
    registryDatabaseIndex: "2"
    trivyAdapterIndex: "5"
    harborDatabaseIndex: "6" //<8>
    cacheLayerDatabaseIndex: "7"//<9>
    username: "" //<10>
    password: ""
    existingSecret: "" //<11>
----
[callouts]
<1> Fill the database connection details in the `external` section.
<2> If using an existing secret, the value must be `password`.
<3> Accepts one of the folowing values:
  disable:: Do not use SSL.
  require:: Always use SSL and skip verification.
  verify-ca:: Always use SSL. Verify that the certificate presented by the server was signed by a trusted CA.
  verify-full:: Always use SSL. Verify that the certificate presented by the server was signed by a trusted CA and the server host name matches the one in the certificate.
<4> Fill the connection information in the `external` section.
<5> Supports redis and redis+sentinel. +
  Address for redis is `<redis_host>:<redis_port>`. +
  Address for redis+sentinel is `<sentinel1_host>:<sentinel1_port>``,`<sentinel2_host>:<sentinel2_port>`,`<sentinel3_host>:<sentinel3_port>`
<6> The name of the set of {redis} instances to monitor. It must be set to support redis+sentinel.
<7> Must be `0` as the library that Harbor uses does not support configurations.
<8> Optional. Defaults to `0` but can be configured to `6`.
<9> Optional. Defaults to `0` but can be configured to `7`.
<10> If empty, it is authenticated against the default user.
<11> If used, the key must be <REDIS_PASSWORD>.